export default {
  config: {
    locales: [
      // 'ar',
      // 'fr',
      // 'cs',
      // 'de',
      // 'dk',
      "es",
      // 'he',
      // 'id',
      // 'it',
      // 'ja',
      // 'ko',
      // 'ms',
      // 'nl',
      // 'no',
      // 'pl',
      // 'pt-BR',
      // 'pt',
      // 'ru',
      // 'sk',
      // 'sv',
      // 'th',
      // 'tr',
      // 'uk',
      // 'vi',
      // 'zh-Hans',
      // 'zh',
    ],
    translations: {
      es: {
        "global.settings": "Ajustes",
        "global.profile": "Perfil",
        "global.content-manager": "Administrador de contenido",
        Name: "Nombre",
        Description: "Descripción",
        "Token type": "Tipo de token",
        "Created at": "Creado",
        "Settings.apiTokens.createPage.title": "Crear token de API",
        "Settings.apiTokens.form.name": "Nombre",
        "Settings.apiTokens.form.description": "Descripción",
        "Settings.apiTokens.form.type": "Tipo de token",
        "global.details": "Detalles",
        "global.save": "Guardar",
        "Settings.roles.form.input.url": "URL",
        "app.utils.delete": "Borrar",
      },
    },
  },
  bootstrap(app) {
    console.log(app);
  },
};
